import { LeadWizard } from "@/components/lead-wizard";
import { ArrowRight, BadgeCheck, Clock3, ShieldCheck } from "lucide-react";
export default function Home(){return <main>
  <nav><a className="brand" href="#">CLICK <span>NUVIA</span></a><a className="phone" href="tel:+18005550199">(800) 555-0199</a></nav>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">REMODEL WITH CONFIDENCE</p><h1>Your dream home.<br/><em>Built around you.</em></h1><p className="lede">Tell us about your project and connect with a qualified remodeling professional serving your area.</p><a className="primary" href="#estimate">Get my free estimate <ArrowRight size={18}/></a><div className="trust"><span><ShieldCheck/> No obligation</span><span><Clock3/> Takes 60 seconds</span><span><BadgeCheck/> Vetted professionals</span></div></div><div className="hero-art"><div className="project-card"><small>POPULAR PROJECT</small><strong>Kitchen remodeling</strong><span>Designed for how you live.</span></div></div></section>
  <section className="steps"><p className="eyebrow">HOW IT WORKS</p><h2>A better path to your remodel</h2><div className="step-grid">{[["01","Share your vision","Answer a few simple questions about your home and goals."],["02","Get matched","We connect you with the right local remodeling professional."],["03","Plan with confidence","Discuss options, timeline and a personalized estimate."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section id="estimate" className="estimate"><div><p className="eyebrow">FREE PROJECT ESTIMATE</p><h2>Let’s bring your vision to life.</h2><p>Start with your project type. Your information is private and only used to help with your request.</p></div><LeadWizard/></section>
  <footer><a className="brand" href="#">CLICK <span>NUVIA</span></a><p>© 2026 Click Nuvia. All rights reserved.</p><p><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></p></footer>
  </main>}
