"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
const projects=["Kitchen","Bathroom","Whole home","Room addition","ADU","Exterior","Other"];
type Form={projectType:string;zip:string;timeline:string;ownership:string;budget:string;firstName:string;lastName:string;email:string;phone:string;consent:boolean;source?:string};
const initial:Form={projectType:"",zip:"",timeline:"",ownership:"",budget:"",firstName:"",lastName:"",email:"",phone:"",consent:false};
export function LeadWizard(){const [step,setStep]=useState(0),[form,setForm]=useState(initial),[status,setStatus]=useState<"idle"|"loading"|"done"|"error">("idle"); const set=(k:keyof Form,v:string|boolean)=>setForm(f=>({...f,[k]:v}));
const submit=async()=>{setStatus("loading");const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,source:new URLSearchParams(location.search).get("utm_source")||"direct"})});setStatus(r.ok?"done":"error")};
if(status==="done")return <div className="success"><CheckCircle2/><h3>Thank you, {form.firstName}.</h3><p>Your project request is in. A remodeling specialist will contact you shortly.</p></div>;
const valid=[!!form.projectType,/^\d{5}$/.test(form.zip),!!form.timeline&&!!form.ownership&&!!form.budget,!!form.firstName&&!!form.lastName&&/^\S+@\S+\.\S+$/.test(form.email)&&form.phone.replace(/\D/g,"").length>=10&&form.consent][step];
return <div className="wizard"><div className="progress"><span style={{width:`${(step+1)*25}%`}}/></div><small>STEP {step+1} OF 4</small>
{step===0&&<fieldset><legend>What would you like to remodel?</legend><div className="choices">{projects.map(p=><button type="button" className={form.projectType===p?"selected":""} onClick={()=>set("projectType",p)} key={p}>{p}</button>)}</div></fieldset>}
{step===1&&<fieldset><legend>Where is the project?</legend><label>ZIP code<input inputMode="numeric" maxLength={5} value={form.zip} onChange={e=>set("zip",e.target.value.replace(/\D/g,""))} placeholder="e.g. 90210"/></label><p className="hint">We use this to confirm service availability.</p></fieldset>}
{step===2&&<fieldset><legend>Help us understand your plans</legend><label>When are you hoping to start?<select value={form.timeline} onChange={e=>set("timeline",e.target.value)}><option value="">Select timeline</option><option>As soon as possible</option><option>1–3 months</option><option>3–6 months</option><option>Just researching</option></select></label><label>Do you own the property?<select value={form.ownership} onChange={e=>set("ownership",e.target.value)}><option value="">Select one</option><option>Yes</option><option>Under contract</option><option>No</option></select></label><label>Estimated budget<select value={form.budget} onChange={e=>set("budget",e.target.value)}><option value="">Select budget</option><option>Under $15,000</option><option>$15,000–$30,000</option><option>$30,000–$75,000</option><option>$75,000–$150,000</option><option>$150,000+</option></select></label></fieldset>}
{step===3&&<fieldset><legend>Where should we send your estimate?</legend><div className="two"><label>First name<input value={form.firstName} onChange={e=>set("firstName",e.target.value)}/></label><label>Last name<input value={form.lastName} onChange={e=>set("lastName",e.target.value)}/></label></div><label>Email<input type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></label><label>Phone<input type="tel" value={form.phone} onChange={e=>set("phone",e.target.value)}/></label><label className="consent"><input type="checkbox" checked={form.consent} onChange={e=>set("consent",e.target.checked)}/><span>By submitting, I agree to be contacted about my project by phone, email or text, including automated technology. Consent is not a condition of purchase. Message and data rates may apply.</span></label></fieldset>}
{status==="error"&&<p className="error">We couldn’t submit your request. Please try again.</p>}<div className="actions">{step>0&&<button className="back" onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button>}<button className="next" disabled={!valid||status==="loading"} onClick={()=>step<3?setStep(s=>s+1):submit()}>{step<3?"Continue":status==="loading"?"Submitting…":"Request my estimate"}<ArrowRight/></button></div></div>}
